#!/bin/sh

start() {
        printf "Loading modules: "
        modprobe -a brcmfmac brcmutil i2c-bcm2835 i2c-dev ppp_generic
        [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
        printf "Unloading modules: "
        rmmod brcmfmac brcmutil i2c-bcm2835 i2c-dev ppp_generic
        [ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
        stop
        sleep 1
        start
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart|reload)
                restart
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac

exit $?
