#!/bin/sh

start() {
        printf "Initializing LCD: "
        i2cset -y 1 0x3e 0 0x38 0x39 0x14 0x74 0x5e 0x6c i && \
        sleep 0.25 && \
        i2cset -y 1 0x3e 0 0x0c 0x01 0x06 i && \
        sleep 0.05 && \
        i2cset -y 1 0x3e 0x40 67 111 110 110 101 99 116 i && \
        sleep 0.05 && \
        i2cset -y 1 0x3e 0x00 0xa8 i && \
        sleep 0.05 && \
        i2cset -y 1 0x3e 0x40 87 105 70 105 i
        [ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
        start)
                start
                ;;
        stop)
                ;;
        restart)
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac

exit $?
