#!/bin/sh

start() {
        printf "Staring LCD updating daemon: "
        start-stop-daemon -S -q -p /var/run/update-lcd.pid -m --background -x /usr/local/bin/update-lcd
        [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
        printf "Stopping LCD updating daemon: "
        start-stop-daemon -K -q -p /var/run/update-lcd.pid -x /usr/local/bin/update-lcd
        [ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
        stop
        sleep 1
        start
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart|reload)
                restart
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac

exit $?
